---
title: "Client Report - What's in a name?"
subtitle: "Course DS 250"
author: "Brett Jameson"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: true
  output: true #addon
    
---

### Introduction

```{python}
#| label: Elevator Pitch
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[(theNames['name'] == "Elliot")]

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total", color = "name"))
    + geom_path(size=1, color="blue")
    + labs(
        title="Ellot... What?",
        x="Year",
        y="Total",
        color="name",
    )
    + scale_x_continuous(format="d")
    + scale_x_continuous(limits=(1950, 2020))
    + theme(
        panel_background=element_rect(color="black", fill="#90d5ff", size=2)
    )
    + geom_segment(x=1982, y=0, xend=1982, yend=1250, color="red", linetype="dashed")
    + geom_segment(x=1985, y=0, xend=1985, yend=1250, color="red", linetype="dashed")
    + geom_segment(x=2002, y=0, xend=2002, yend=1250, color="red", linetype="dashed")
    + scale_y_continuous(limits=(0, 1250))
    + geom_text(x=1981, y=1250, label="E.T Released", label_size=0, hjust="right", color="black", size="5")
    + geom_text(x=1986, y=1250, label="Second Release", label_size=0, hjust="left", color="black", size="5")
    + geom_text(x=2003, y=1250, label="Third Release", label_size=0, hjust="left", color="black", size="5")
)
```


## Elevator pitch

_It is fascinating to look at how modern media effects the names that parents give their children, as you can see by looking at the chart above. Sometimes however the relationship isn't as obvious and requires a deeper dive in order to understand what the data is telling us. Many times it is not a single event that has an effect on a names popularity but a combination of events. The effect that each new event has upon the data alters the graph and it is a data scientists job to be able to identify the underlying data. It is also important to label the data to help ensure that your audience will be able to easily see the story that your data is telling them._

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

While the name Brett was around prior to the 1950s, it wasn't until the mid 1950s where the popularity of the name began to take off. In 1977, the year that I was born, my name was nearing the height of it's popularity, with about 3000 people being given the name Brett in that year.

```{python}
#| label: Q1
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[theNames['name'] == "Brett"]

filteredNames = filteredNames.astype({"Total": "int", "name": "string", "year": "int"})

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total"))
    + geom_point(size=2)
    + labs(
        title="Historical Naming Frequency",
        x="Year",
        y="Total Children Named Brett",
        color="name",
    )
    + scale_x_continuous(format="d")
    + geom_smooth(method="loess", size=1)
    + geom_segment(x=1955, y=3500, xend=1977, yend=2979, arrow=arrow(type="closed"), color="red")
    + geom_label(x=1955, y=3500, label="Year Born (1977)", hjust="left", 
    color="red")
    + scale_y_continuous(limits=(0, 4100))
    + scale_x_continuous(limits=(1950, 2015))
)
```

## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

The most likely year that a person named Brittany was born would be in 1990 which would place her at 34 years old. This is where the name was most popular with over 32000 children being named Brittany. According to the data the name Brittany was not around prior to 1968 so I would not guess ages greater than 56.

```{python}
#| label: Q2
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[theNames['name'] == "Brittany"]

filteredNames = filteredNames.astype({"Total": "int", "name": "string", "year": "int"})

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total"))
    + geom_point(size=2)
    + labs(
        title="Historical Naming Frequency",
        x="Year",
        y="Total Children Named Brittany",
        color="name",
    )
    + scale_x_continuous(format="d")
    + geom_smooth(method="loess", size=1)
    + geom_segment(x=1965, y=30000, xend=1990, yend=32562, arrow=arrow(type="closed"), color="red")
    + geom_label(x=1965, y=30000, label="Most Likely Year is 1990 - 34yrs Old", hjust="left", 
    color="red")
    + scale_x_continuous(limits=(1965, 2015))
    + scale_y_continuous(limits=(0, 34000))
)
```

## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

Right off there are three trends here that I am noticing. First, as these are biblical names the popularity of each one of them save Martha see an uptick in popularity around the time of WW2. With the uncertainty that war and pre-war times bring I am not surprised that more biblical rooted names would begin to emerge as people turned to religion for comfort.

There are two exceptions to this observation.

- First the name Martha actually sees a decline in popularity at this same point in time. My thoughts as to the reason for this is primarily rooted in the fact that she is a more minor character in the bible and as such of lesser known than the other names.

- Second, the name Mary had a second rise to popularity that spiked at around the year 1921. In doing a little research it seems that Mary was a symbol of protection durring WW1 and so my hypothesis is that this may be the reason why we are seeign that second spike before the curve aligns with the other biblical figure names.

```{python}
#| label: Q3
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[(theNames['name'] == "Mary") | (theNames['name'] == "Martha") | (theNames['name'] == "Peter") | (theNames['name'] == "Paul")]

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total"))
    + geom_point(aes(colour="name"))
    + scale_x_continuous(format="d")
    + geom_smooth(method="loess", size=1)
    + scale_x_continuous(limits=(1920, 2000))
)
```

## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

For a famous movie, I selected Casablanca. The main character in that movie is Victor and I thought there would be a marked increase in that name's usage considering the popularity of the movie. What I found was that, while there was an uptick, it was not the movie, but some other event that transpired in the late 1930s that gave rise to the name's popularity. This would suggest that the name of the main character from that movie was selected due to the event in the late 1930s. Following Casablanca's release the name continued to rise higher, so I suspect that while not the original source of the increae in popularity, it probably served to spur the name's use on to greater heights.

```{python}
#| label: Q4
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[(theNames['name'] == "Victor")]

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total"))
    + geom_point(size=2)
    + labs(
        title="Historical Naming Frequency",
        x="Year",
        y="Total Children Named Victor",
        color="name",
    )
    + scale_x_continuous(format="d")
    + geom_smooth(method="loess", size=1)
    + geom_segment(x=1925, y=3500, xend=1942, yend=2392, arrow=arrow(type="closed"), color="red")
    + geom_label(x=1910, y=3500, label="Casablanca (1942)", hjust="left", 
    color="red")
)
```

## QUESTION|Stretch

__Reproduce the chart Elliot using the data from the names_year.csv file.__

```{python}
#| label: Stretch
#| include: true
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=False)
theNames = pd.read_csv("data/names_year.csv")

# Filter out all but the desired names
filteredNames = theNames[(theNames['name'] == "Elliot")]

(ggplot(data = filteredNames, mapping = aes(x = "year", y = "Total", color = "name"))
    + geom_path(size=1, color="blue")
    + labs(
        title="Ellot... What?",
        x="Year",
        y="Total",
        color="name",
    )
    + scale_x_continuous(format="d")
    + scale_x_continuous(limits=(1950, 2020))
    + theme(
        panel_background=element_rect(color="black", fill="#90d5ff", size=2)
    )
    + geom_segment(x=1982, y=0, xend=1982, yend=1250, color="red", linetype="dashed")
    + geom_segment(x=1985, y=0, xend=1985, yend=1250, color="red", linetype="dashed")
    + geom_segment(x=2002, y=0, xend=2002, yend=1250, color="red", linetype="dashed")
    + scale_y_continuous(limits=(0, 1250))
    + geom_text(x=1981, y=1250, label="E.T Released", label_size=0, hjust="right", color="black", size="5")
    + geom_text(x=1986, y=1250, label="Second Release", label_size=0, hjust="left", color="black", size="5")
    + geom_text(x=2003, y=1250, label="Third Release", label_size=0, hjust="left", color="black", size="5")
)
```